GET http://localhost:3001/api/items/4

###
POST http://localhost:3001/api/staffs
Content-Type: application/json

{
    "username": "admintest",
    "password": "123456",
    "positionId": 1,
    "salary": 55555.0,
    "shopId": 1,
    "dateStart": "1980-01-01",
    "firstname": "Test",
    "lastname": "Tester",
    "nationId": "1234567890123",
    "dateBirth": "1980-01-01",
    "address": "unknownnnn!",
    "tel": "1234567890",
    "email": "test@tester.com"
}

###
POST http://localhost:3001/api/branches
Content-Type: application/json

{
    "name": "Test branch",
    "address": "Test address of this branch",
    "tel": "1234567890",
    "dateStart": "1980-01-01"
}

# POST http://localhost:3001/api/items/ HTTP/1.1
# content-type: application/json

# {
#     "tracking_no": "ddd",       
#     "sender_name": "send name",      
#     "sender_tel": "444444444",     
#     "sender_idcard": "123445678875",    
#     "sender_address": "address test sender",   
#     "receiver_name": "receive name",  
#     "receiver_tel": "444444444", 
#     "receiver_address": "address test receive"
# }



# PUT http://localhost:3001/api/items/4 HTTP/1.1
# content-type: application/json

# {
#   "sender_tel": "44444455",
#   "receiver_tel": "44444455"
# }